# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3adf8841b900a325713cb55038a24a69eae8e37417f9a6e15643944f1a79fad64e32c9a7925bee4d7062994768a85147d43c770d1c366b9597a0dffa932cd894

test:
  secret_key_base: 770bdbbb081087b31e79c7fd037c021ab845abcc8adba0e633cb1d112a2b563cfda26e4e6f25d4c05c3a55f1e89304554489633a62f3fc3e213d9a9f31b0f661

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
